#!/usr/bin/perl

use strict;
use warnings;
use Term::Cap;
use Term::ReadLine;
use Switch;
$|++;

# Subs {{{

sub say { print shift . "\n"; }

# }}}
# Initialization {{{

my $term = Term::Cap->Tgetent({OSPEED => 9600});
my $termClear = $term->Tputs('cl');
sub clear { print $termClear; }

my $rlterm = Term::ReadLine->new('Caverns of Coq');
$rlterm->ornaments(0);

# TODO quit if size < 80x24

my %state = (
  room => 'clearing'
);

# }}}
# Input loop {{{

while (defined(my $input = $rlterm->readline('> '))) {
  switch ($input) {
    case (/exit/) {
      exit;
    }
    say "You said: $input";
  }
}

#clear;
print <<'END';
"WELCOME TO CAVERNS OF COQ!

CoC is a game of adventure, danger, and low cunning. In it you will explore some
of the most amazing theorems ever proven by mortal man. No computer scientist
should be without one!"

END

# }}}
# Rooms {{{

my %rooms = (
  clearing =>
    (n => 1)
);

# }}}

